name: causal_eeg_vae
channels:
  - conda-forge
  - pyg
  - pytorch
  - huggingface
dependencies:
  - python
  - pandas
  - matplotlib
  - numpy
  - nltk
  - pyg
  - pytorch 
  - torchvision 
  - torchaudio 
  - torchtext
  - cpuonly
  - transformers
  - pip
  - pip:
    - -e ../seldonite/.